version: "3"
services:
  frontend:
    container_name: drupal9_jamesini_frontend
    # build: . # use this if you want to build the image locally
    image: "uwbfritz/d9frontend:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/php.ini:/usr/local/etc/php/php.ini:cached
      - ./config/apache2.conf:/etc/apache2/apache2.conf:cached
      - ./config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:cached
      - html:/var/www/html
      - private:/home/d9privatefiles
      - public:/var/www/html/web/sites/default/files
      - temp:/home/d9tempfiles
      
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
        
    links:
      - db
  db:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: jamesini*
      MYSQL_DATABASE: drupal9_jamesini
      MYSQL_USER: drupal9_jamesini
      MYSQL_PASSWORD: drupal9_jamesini
volumes:
  mysql:
  html:
  private:
  public:
  temp: